config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/team', to: 'pages#team', as: 'team'
  resources :requests, only: [:index, :show, :update]
  namespace :rider do
    resources :requests, only: [:index]
  end
  namespace :customer do
    resources :requests, only: [:index, :new, :create, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/indian.rb
class Indian
  attr_reader :name

  def initialize
    init_arrays
    @name = new_name
  end

  private
  def check_tribe
    Request.where.not(code: nil).map {|k| k.code}
  end

  def init_arrays
    @description = %w(Petit Grand Joli Elégant Gros)
    @animal = %w(Lapin Renard Bison Mulot Faucon Serpent)
    @skill = %w(Malin Rapide Agile Sympa Sérieux Vaillant Bavard)
  end

  def random_name
    "#{@description.sample} #{@animal.sample} #{@skill.sample}"
  end

  def new_name
    tribe = check_tribe
    name = random_name
    while tribe.include?(name)
      name = random_name
    end
    name
  end


end

app/models/location.rb
class Location < ApplicationRecord
  has_one :departure_request, foreign_key: "departure_id", class_name: "Request"
  has_one :arrival_request, foreign_key: "arrival_id", class_name: "Request"

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :customer, class_name: 'User'
  belongs_to :rider, class_name: 'User', optional: true
  belongs_to :departure, class_name: 'Location'
  belongs_to :arrival, class_name: 'Location'

  validates :departure, presence: true
  validates :arrival, presence: true
  validates :parcel, presence: true

  enum status: [ :created, :pending, :done ]

  def self.parcel_type_icon(parcel)
      case parcel
        when 0 then return 'icons/envelope.svg'
        when 1 then return 'icons/basket.svg'
        when 2 then return 'icons/sofa.svg'
      end
  end

  def parcel_icon
    Request.parcel_type_icon(self.parcel)
  end

  def explicit_status
    case self.status
      when 'created' then return 'commandé'
      when 'pending' then return 'en cours'
      when 'done' then return 'livré'
    end
  end

  def prepare
    set_distance
    set_price
  end

  private

  def set_distance
    self.distance = self.departure.distance_to([self.arrival.latitude, self.arrival.longitude])
  end

  def set_price
    distance_coef = [0.8, 1, 1.5]
    fix = [0.5, 1, 1.5]
    self.price = ((distance_coef[self.parcel] * self.distance) + fix[self.parcel]).round
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :customer_requests, foreign_key: "customer_id", class_name: "Request"
  has_many :rider_requests, foreign_key: "rider_id", class_name: "Request"

  def anonymize
    "#{first_name} #{last_name[0].upcase}."
  end

  def to_s
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :store_current_location, :unless => :devise_controller?

  private

  def store_current_location
    store_location_for(:user, request.url)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/customer/customer_requests_controller.rb
class Customer::RequestsController < ApplicationController

  def index
    current_user = User.find(1)
    @requests = current_user.requests
    byebug
  end

  def new
  end

  def create
  end

end

app/controllers/customer/requests_controller.rb
class Customer::RequestsController < ApplicationController

  skip_before_action :authenticate_user!, only: :new

  def index
    @customer_requests = current_user.customer_requests
  end

  def new
    @request = Request.new
  end

  def create
    parameters = {
      description: customer_request_params[:description],
      parcel: customer_request_params[:parcel],
      distance: customer_request_params[:distance],
      price: customer_request_params[:price],
      polyline: customer_request_params[:polyline],
      customer: current_user,
      departure: Location.create(address: customer_request_params[:departure]),
      arrival: Location.create(address: customer_request_params[:arrival])
    }

    @request = Request.new(parameters)

    # @request.prepare

    if @request.save
      redirect_to customer_requests_path
    else
      render :new
    end
  end

  def update
    # byebug
    @request = Request.find(params[:id])
    @request.status = 2
    if @request.save
      respond_to do |format|
        format.html { redirect_to customer_requests_path }
        format.js  # <-- will render `app/views/requests/update.js.erb`
      end
      #redirect_to rider_requests_path
    else
      respond_to do |format|
        format.html { render 'customer/requests/index' }
        format.js  # <-- will render `app/views/requests/update.js.erb`
      end
    end

  end

  private

  def customer_request_params
    params.require(:request).permit(:description, :departure, :arrival, :parcel, :distance, :price, :polyline)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :team ]

  def home
  end

  def team
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  skip_before_action :authenticate_user!, only: :index
  before_action :set_request, only: [:show, :update]

  def index

    @requests = Request.all

    if params[:search].nil? || params[:search][:address].empty?
      @searched_address = '107 cours Balguerie Stuttenberg, 33000 Bordeaux'
      @searched_radius = 5
    else
      @searched_address = params[:search][:address]
      @searched_radius = params[:search][:radius].to_i
    end
    # if params[:search][:radiu].nil?
    #   searched_radius = 5
    # else
    #   searched_radius = params[:search][:radiu].to_i
    # end

    #@departures = Location.joins("INNER JOIN requests ON locations.id = requests.departure_id")
                           #.near(searched_address, searched_radius)
                          #.where.not(latitude: nil, longitude: nil)
                         #.where.not("locations.latitude = ? AND locations.longitude = ?", nil, nil)
    @departures = Location.joins(:departure_request)
                           .near(@searched_address, @searched_radius).uniq!
                          #.where.not(latitude: nil, longitude: nil)
                         #.where.not("locations.latitude = ? AND locations.longitude = ?", nil, nil)
    @departures_nb = @departures.length

    @hash = Gmaps4rails.build_markers(@departures) do |departure, marker|
      marker.lat departure.latitude
      marker.lng departure.longitude
      marker.infowindow render_to_string(partial: "/requests/map_box", locals: { departure: departure })
    end

    @hash_rider = {
      lat: Geocoder.coordinates(@searched_address).first,
      lng: Geocoder.coordinates(@searched_address).last,
      picture: {
        :url     => 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
        :width   => 32,
        :height  => 32
        }
    }

    @hash << @hash_rider

  end

  def show
  end

  def update
    # byebug
    @request.rider = current_user
    @request.status = 1
    # appel de la methode privée qui génère un code
    @request.code = Indian.new.name
    if @request.save
      respond_to do |format|
        format.html { redirect_to request_path(@request) }
        format.js  # <-- will render `app/views/requests/update.js.erb`
      end
      #redirect_to rider_requests_path
    else
      respond_to do |format|
        format.html { render 'requests/show' }
        format.js  # <-- will render `app/views/requests/update.js.erb`
      end
    end
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end


end

app/controllers/rider/requests_controller.rb
class Rider::RequestsController < ApplicationController
  def index
    requests = current_user.rider_requests
    @rider_requests = requests.where(status: 1)
    @rider_done = requests.where(status: 2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customer/requests/index.html.erb
<div class="client-background wrapper-show">
  <div class="btn-customer-index">
    <%= link_to new_customer_request_path do %>
    <button class="btn btn-client">Créer une nouvelle demande</button>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <% @customer_requests.each do |request| %>
      <div class="col-lg-4">
        <div class="course-card center-show">
        <div class="card-header">
          <h4 class="small-header">Course n° <%= request.id %></h4>
        </div>
        <div>
          <p class="price"><%= request.price.round %>€</p>
        </div>
          <div class="course-description">
            <h2 class="small-header small-header-desc"><%= request.description %></h2>
          </div>
          <div class="course-status">
            <% if request.status == "pending" %>
            Code : <%= request.code %><br>
            <% end %>
          </div>
          <div class="status-wrapper">
            <% status_0 = "off" %>
            <% status_1 = "off" %>
            <% status_2 = "off" %>
            <% case request.status %>
            <% when "created" then status_0 = "on" %>
            <% when "pending" then status_1 = "on" %>
            <% when "done" then status_2 = "on"%>
            <% end %>
            <%= content_tag(:div, class: "status-indicator si-#{status_0}") do %>
            commandé
            <% end %>
            <%= content_tag(:div, class: "status-next sn-#{status_0}") do %>
            <i class="fa fa-caret-right fa-2x" aria-hidden="true"></i>
            <% end %>
            <%= content_tag(:div, class: "status-indicator si-#{status_1}", id: "s-in-#{request.id}") do %>
            en cours
            <% end %>
            <%= content_tag(:div, class: "status-next sn-#{status_1}", id: "sn-#{request.id}") do %>
            <i class="fa fa-caret-right fa-2x" aria-hidden="true"></i>
            <% end %>
            <%= content_tag(:div, class: "status-indicator si-#{status_2}", id: "s-out-#{request.id}") do %>
            livré
            <% end %>
          </div>
          <% if request.status == "pending" %>
          <%= link_to "Je confirme la réception", customer_request_path(request) , id: "btn-delivered-#{request.id}", class: "btn btn-client btn-client-index", method: :put, remote: true %> <br>
          <% end %>
          <button class="btn btn-chevron" type="button" data-toggle="collapse" data-target="#collapseExample<%=request.id%>" aria-expanded="false" aria-controls="collapseExample">
          <i class="fa fa-chevron-down" aria-hidden="true"></i>
          </button>
          <div class="collapse" id="collapseExample<%=request.id%>">
            <div class="well">
              <p>Adresse de retrait : <%= request.departure.address %></p>
              <p>Adresse de livraison : <%= request.arrival.address %></p>
              <p>Distance : <%= request.distance.round %>km - Type de colis : <%= image_tag request.parcel_icon, class: "parcel-icon-logo"%></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/requests/new.html.erb
<div class="client-background">
  <div class="form-wrapper">
    <h2 class="small-header">Créer une nouvelle demande</h2>
    <%= simple_form_for @request, url: customer_requests_path, method: "POST" do |f| %>
      <%= f.error_notification %>

      <%= f.input :description %>
      <%= f.input :departure,label: "Adresse de départ", input_html: {id: "departure_address"} %>
      <%= f.input :arrival, label: "Adresse d'arrivée", input_html: {id: "arrival_address"} %>
      <%= f.label "Type de colis" %>
      <%= f.input :polyline, as: :text, input_html: {id: "polyline", class: "hidden"}, label:false %>
      <%= f.input :distance, as: :float, input_html: {id: "distance", class: "hidden"}, label:false %>
      <%= f.input :price, as: :float, input_html: {id: "price", class: "hidden"}, label:false %>
      <div style="display: flex; justify-content: space-between;width: 30%">
      <%= f.collection_radio_buttons(:parcel, [['S',0],['M',1],['L',2]], :last, :first, input_html: {id: "parcel_type"} , item_wrapper_tag: :div, checked: 2 ) do |b| %>
        <% b.label { b.radio_button + " " + image_tag(Request.parcel_type_icon(b.value), style: 'height:20px; width:20px;') } %>
        <% end %>
      </div>
      <div class="form-confirm hidden" style="background: grey; color: white;padding: 5px;">
        <div class="row">
          <div class="col-xs-12">
            <div class="price-tag" >
                <div class="booked booked-show">
                  <p id="display_distance">Distance:</p>
                  <p id="display_price">Prix de la course : 2 €</p>
                </div>
              </div>
              <%= f.button :submit, "Valider la demande", class: "btn-client btn-show" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>


<%= content_for(:after_js) do %>
  <script type="text/javascript">
  $(document).on('ready', function() {

    function initialize() {
      var departure_input = document.getElementById('departure_address');
      var arrival_input = document.getElementById('arrival_address');
      var autocomplete = new google.maps.places.Autocomplete(departure_input);
      var autocomplete = new google.maps.places.Autocomplete(arrival_input);
    }
    google.maps.event.addDomListener(window, 'load', initialize);

    var directionsService = new google.maps.DirectionsService();
    var directionsDisplay = new google.maps.DirectionsRenderer();

    function calcRoute(departure, arrival) {
      var origin      = String(departure);
      var destination = String(arrival);
      var request = {
          origin:      origin,
          destination: destination,
          travelMode:  google.maps.TravelMode.BICYCLING
      };
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          // calcul distance
          var result = response["routes"][0]["legs"][0]["distance"]["value"];
          $('#display_distance').html('<p>Distance : ' + result/1000 + ' km</p>');
          $('#distance').val(result/1000);
          // get polyligne
          var polyline = response["routes"][0]["overview_polyline"];
          $('#polyline').val(polyline);
          console.log(polyline);
          // calcul price
          var parcel = 1;
          if ($('#request_parcel_0').is(':checked') === true) {parcel = 0};
          if ($('#request_parcel_1').is(':checked') === true) {parcel = 1};
          if ($('#request_parcel_2').is(':checked') === true) {parcel = 2};
          console.log(parcel);
          var distance_coef = [0.8, 1, 1.5];
          var fix = [0.5, 1, 1.5];
          var price = ((distance_coef[parcel] * result/1000) + fix[parcel]);
          console.log(price);
          $('#display_price').html('<p>Prix de la course : ' + Math.round(price) + ' €</p>');
          $('#price').val(price);
        }
      });
    }

    function testAddressFields() {
      var from = $("#departure_address").val();
      var to = $("#arrival_address").val();
      if ( from && to) {
        // calcul distance and price
        calcRoute(from, to);
        $('.form-confirm').removeClass('hidden');
      };
    };

    $("#departure_address").change(function() {
      testAddressFields();
    });
    $("#arrival_address").change(function() {
      testAddressFields();
    });
    $("#request_parcel_0").click(function() {
      testAddressFields();
    });
    $("#request_parcel_1").click(function() {
      testAddressFields();
    });
    $("#request_parcel_2").click(function() {
      testAddressFields();
    });
  });

  </script>
<% end %>

app/views/customer/requests/update.js.erb
$("#s-in-<%= @request.id %>").toggleClass("si-on");
$("#s-in-<%= @request.id %>").toggleClass("si-off");
$("#s-out-<%= @request.id %>").toggleClass("si-off");
$("#s-out-<%= @request.id %>").toggleClass("si-on");
$("#sn-<%= @request.id %>").toggleClass("sn-on");
$("#sn-<%= @request.id %>").toggleClass("sn-off");
$("#btn-delivered-<%= @request.id %>").addClass("hidden");
//$("#div-done-delivered-<%= @request.id %>").removeClass("hidden");

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <h1>DailyVery</h1>, les livraisons de votre quotidien
  </div>
  <div class="meet-team desktop">
    <%= link_to team_path, class: "navbar-wagon-item navbar-wagon-link" do %>
      Rencontrez la team <h1>DailyVery</h1>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyVery</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_KEY']}" %>
      <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
      <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>
      <%= javascript_include_tag 'application' %>
      <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-logo">
  <div class="home-brand-name">
    <h1>DailyVery</h1>
    <p>Les livraisons de votre quotidien</p>
  </div>
</div>

<div class="home-wrapper">
  <div class="rider-side" style="background-image: url(<%= image_path('rider.jpg') %>); background-size: cover;">
    <div class="rider-overlay">
      <%= button_to "Je cherche à livrer", requests_path, class: "btn btn-rider btn-rider-margin", method: :get %>
    </div>
  </div>
  <div class="client-side" style="background-image: url(<%= image_path('basket.jpg') %>); background-size: cover;">
    <div class="client-overlay">
      <%= button_to "Je souhaite une livraison", new_customer_request_path, class: "btn btn-client btn-client-margin", method: :get %>
    </div>
  </div>
</div>


 <%= content_for :after_js do %>
    <script type="text/javascript">
      $(".btn-rider").click(function () {
          $( document.body ).toggle( "slide", {direction: "right"} );
        });
      $(".btn-client").click(function () {
          $( document.body ).toggle( "slide", {direction: "left"} );
        });
    </script>
<% end %>

app/views/requests/_booked.html.erb
<div class="booked">
  <h4 class="small-header"> Vous avez pris ce ride !</h4>
  <p style="font-size: 20px;">Code commerçant : </p>
  <p class="code" style="font-size: 20px;"><%= request.code.upcase %> </p>
</div>

app/views/requests/_map_box.html.erb
<%= link_to request_path(departure.departure_request) do %>
  <div class="card">
    <div class="card-category"> <%= image_tag departure.departure_request.parcel_icon %> </div>
    <div class="card-distance"> Distance à parcourir : <%= departure.departure_request.distance.round %> km</div>
    <div class="card-description">
      <p><strong><%= departure.departure_request.description %></strong></p>
      <p class= "arrival_ad">A livrer au : <br> <%= departure.departure_request.arrival.address %></p>
    </div>
    <div class="card-price"><%=  departure.departure_request.price.round%> €</div>
  </div>
<% end %>

app/views/requests/index.html.erb
<div class="rider-background">
  <div class="container">
    <%= simple_form_for :search, url: requests_path, method: :get do |f| %>
      <div class="row">
        <div class="col-lg-6 col-xs-12">
          <%= f.input :address, as: :string, input_html: {id: "address", value: @searched_address, class: "form-search form-search-input"}, required: true, autocomplete: "on", label:false %>
        </div>
        <div class="col-lg-6 col-xs-12">
          <div class="search-form-requests">
            <div class="un">
              <div class="slider">
                 <%= render 'shared/slider' %>
              </div>
              <%= f.input :radius, input_html: { value: @searched_radius }, as: :hidden %>
            </div>
            <div class="deux">
            <div class="hidden-xs hidden-sm">
              <%= f.button( :submit, class: "btn-rider btn-right") do %>
              <i class="fa fa-search" aria-hidden="true"></i>
              <% end  %>
            </div>
            <div class="hidden-md hidden-lg">
              <%= button_tag(type: 'submit', class: "btn-rider btn-right") do %>
                <i class="fa fa-search" aria-hidden="true"></i>
              <% end %>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="desktop">
    <div id="map"></div>
  </div>

  <div class="mobile mobile-index">
    <div class="container">
      <div class="row">
        <% @departures.each do |departure| %>
          <div class="col-lg-4 col-xs-12">
            <div class="index-card center-show">
              <%= link_to request_path(departure.departure_request) do %>
                <h3 class="small-header"> Course n° <%= departure.departure_request.id %></h3>
                Prix : <%= departure.departure_request.price.round %>€ <br>
                <div id="static-map">
                  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?scale=false&size=250x200&maptype=roadmap&format=png&visual_refresh=true&path=weight:3%7Ccolor:blue%7Cenc:#{departure.departure_request.polyline}&markers=size:mid%7Ccolor:red%7Clabel:D%7C#{departure.address}&markers=size:mid%7Ccolor:green%7Clabel:A%7C#{departure.departure_request.arrival.address}&markers=size:mid%7Ccolor:blue%7C#{@searched_address}&key=#{ENV['GOOGLE_API_KEY']}" %>
                </div>
              <% end %>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>


<%= content_for(:after_js) do %>
  <script type="text/javascript">
  $(document).on('ready', function() {
    var directionsDisplay = new google.maps.DirectionsRenderer();
    var directionsService = new google.maps.DirectionsService();

    function initialize() {
      var input = document.getElementById('address');
      var autocomplete = new google.maps.places.Autocomplete(input);
    }
    google.maps.event.addDomListener(window, 'load', initialize);

    function calcRoute(lat_departure, lng_departure, lat_arrival, lng_arrival) {
      console.log('lat_departure :' + lat_departure)
      var origin      = new google.maps.LatLng(lat_departure, lng_departure);
      var destination = new google.maps.LatLng(lat_arrival, lng_arrival);
      var request = {
          origin:      origin,
          destination: destination,
          travelMode:  google.maps.TravelMode.DRIVING
      };
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(response);
        }
      });
    }

    // var contentString =
    //   '<p><b>Uluru</b>, also referred to as <b>Ayers Rock</b>, is a large ' +
    //   'sandstone rock formation in the southern part of the '+
    //   'Northern Territory, central Australia.'

    // var infowindow = new google.maps.InfoWindow({
    //   content: contentString
    // });

    var handler = Gmaps.build('Google');
    handler.buildMap({ internal: { id: 'map' } }, function(){
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      console.log(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      directionsDisplay.setMap(handler.getMap());
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      };
      <%= raw @hash.to_json %>.forEach(function(marker) {
        // Listen if marker is clicked => if clicked : display directions
        google.maps.event.addListener(marker, 'click', function(){
          alert('call calcRoute')
          calcRoute(marker.lat, marker.lng, marker.json.lat_arrival.to_f, marker.json.lng_arrival.to_f);
          directionsDisplay.setMap(handler.getMap());
        });
      })

    });
  });
  </script>
<% end %>

app/views/requests/update.js.erb
<% if @request.errors.any? %>
  // Display flash message

<% else %>
  // Create a paragraph for the new review. But hide it.
  var booked = $("<%= j render 'requests/booked', request: @request %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#booked').html(booked);
  // Show the new review with an animation!
  booked.slideDown();
<% end %>

app/views/rider/requests/index.html.erb
<div class="rider-background">
  <div class="btn-customer-index">
    <%= link_to requests_path do %>
      <button class="btn btn-rider">Chercher d'autres courses disponibles</button>
    <% end %>
  </div>

  <div class="container">
    <div class="row">
      <% @rider_requests.each do |request| %>
        <div class="col-lg-4 col-xs-12">
          <div class="course-card center-show">
            <div class="card-header">
              <h4 class="small-header">Course n° <%= request.id %></h4>
              <h4 class="small-header">Prix : <%= request.price.round %>€</h4>
            </div>
            <div class="course-description">
              <h2 class="small-header small-header-desc"><%= request.description %></h2>
            </div>
            <div class="course-status">
              <% if request.status == "created" %>
                <div class="statut-orange">Statut : <%= request.explicit_status %></div>
                <button class="btn btn-client btn-client-index">Livré</button> <br>
              <%elsif request.status == "pending" %>
                <div class="booked booked-orange" style="font-size: 18px;">
                  Code : <%= request.code.upcase %> <br>
                  Statut : <%= request.explicit_status %>
                </div>
              <% else %>
                  Statut : <%= request.explicit_status %> <br>
                  Code : <%= request.code %>
              <% end %>
              <button class="btn btn-chevron" type="button" data-toggle="collapse" data-target="#collapseExample<%=request.id%>" aria-expanded="false" aria-controls="collapseExample">
                <i class="fa fa-chevron-down" aria-hidden="true"></i>
              </button>
              <div class="collapse" id="collapseExample<%=request.id%>">
                <div class="well">
                  <p>Adresse de retrait : <%= request.departure.address %></p>
                  <p>Adresse de livraison : <%= request.arrival.address %></p>
                  <p>Distance : <%= request.distance.round %>km - Type de colis : <%= image_tag request.parcel_icon, class: "parcel-icon-logo"%></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_iconblue.html.erb
<%= image_tag "icons/blue-dot.png" %>

app/views/shared/_search_bar.html.erb
<%= simple_form_for :search, html: {class: "form-search"}, :method => :get do |f| %>
    <%= f.input :search, autofocus: true, input_html: {class: "form-search-input", placeholder: "Entrer une adresse de retrait"}, label: false %>
<% end %>

app/views/shared/_slider.html.erb
<!-- <input class="lign" type="range" min="0" max="10" value="3" id="fader" step="1" oninput="outputUpdate(value)">
      <output for="fader" id="volume">3</output> -->
<div>
  <div id="slider"></div>
</div>

<%= content_for :after_js do %>
  <script>
  $( function() {
    $(".ui-slider-handle").text(<%= @searched_radius %>  + ' km');
  });
  </script>
<% end %>